name: N8NMUSIC
favicon: null
layout_spectrum: 0.5197122993413359
typography_spectrum: 0.24432012252509594
title: SINGER/DEEJAY/BAND/PROMOTER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0.7550888599362224
  saturation: 0.12042081169784069
  rhythmicContrast: 0.14782878337427974
purpose: []
